# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Geon Choi
email: geon.choi@postech.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral Researcher at Com-X Laboratory, POSTECH, working with Prof. Namyoon Lee. 
  Research interests in information theory, channel coding, and machine learning 
  applications for next-generation wireless systems.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  style: compressed


images: '/assets/images'
